### ISSUE TITLE
BEST=$(shell ...) is broken on OS X

### ISSUE THREAD

**Issue by whitequark** [mjambon/biniou#14]
I'm not sure why exactly, but it's empty. Please consider using OCaml's Makefile.config instead of doing this fragile shell magic.

The workaround is to use `make BEST=.native`.

**Comment by mjambon** [comment]
Thanks. This is unfortunate because I already got rid of the shell assignment operator `!=` last week, which was giving an empty `$(BEST)` with some older version of gnu make. Could you please confirm that you tested this with the latest version of biniou, 1.0.11?

Does the following makefile display something unexpected where you run `make`?
```BEST = $(shell \
  echo hello; \
  if ocamlfind ocamlopt; then \
    echo .native; \
  else \
    echo .byte; \
  fi \
)

default:
	echo "BEST: $(BEST)"
```

If you have ocamlopt, you should get:
```
$ make
echo "BEST: hello .native"
BEST: hello .native
```

**Comment by whitequark** [comment]
That outputs:
```
echo "BEST: hello .native"
BEST: hello .native
```

**Comment by whitequark** [comment]
Ah wait, I'm using biniou 1.0.10... let me try .11.

**Comment by whitequark** [comment]
Ok... this works in 1.0.11. Sorry for the noise!

**Comment by mjambon** [comment]
No problem. It would still be a good thing to get rid of makefiles when it comes to building software for the users (as opposed to development). I'm just not thrilled by oasis, ocamlbuild, etc.
